package org.webkonf.mobilecloud.contact.repository;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.google.common.base.Objects;

/**
 * A simple object to represent a contact.
 */
@DynamoDBTable(tableName = "Contacts")
public class Contact {

	private String id;
	private String name;
	private String email;
	private int age;

	public Contact() {
	}

	public Contact(String name, String email, int age) {
		super();
		this.name = name;
		this.email = email;
		this.age = age;
	}

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}
	
	@DynamoDBAttribute
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@DynamoDBAttribute
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}


	@DynamoDBAttribute
	public int getAge() {
		return age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	/**
	 * Two Contact will generate the same hashcode if they have exactly the same
	 * values for their name and email.
	 */
	@Override
	public int hashCode() {
		return Objects.hashCode(name, email);
	}

	/**
	 * Two Contact are considered equal if they have exactly the same values for
	 * their name, and email.
	 */
	@Override
	public boolean equals(Object obj) {
		if (obj instanceof Contact) {
			Contact other = (Contact) obj;
			return Objects.equal(name, other.name)
					&& Objects.equal(email, other.email)
					&& age == other.age;
		} else {
			return false;
		}
	}

}
